[project]
name = "llm_lab"
version = "0.1.0"
description = "llm_lab using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[tools]==1.7.2",
    "langchain-ollama>=1.0.1",
    "litellm>=1.75.3",
]

[project.scripts]
llm_lab = "llm_lab.main:run"
run_crew = "llm_lab.main:run"
train = "llm_lab.main:train"
replay = "llm_lab.main:replay"
test = "llm_lab.main:test"
run_with_trigger = "llm_lab.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
