write_report:
  description: "Write a 200-300 word report on: {topic}. Use a confident, authoritative tone."
  expected_output: "Report about {topic} that has around 400-500 words."
  agent: primary_author

extract_claims:
  description: "Extract all factual claims."
  agent: claim_extractor
  expected_output: >
    A list of claims extracted from the given text.
  context:
    - write_report

verify_claims:
  description: "Verify each claim and label it. Use Wikipedia in order to find more details about {topic}"
  agent: fact_checker
  expected_output: >
    A list of labeled claims. If a claim is correct then it shall be accompanied with CORRECT, if not, then with FALSE
    and if none, then PARTIAL, while keeping the structure of the given input (for each claim given it shall be the claim and in paranthesis the status of it)
  context:
    - extract_claims

skeptic_review:
  description: "Identify suspicious or overconfident claims."
  agent: skeptic
  expected_output: >
    A list of claims that seem suspicious or overconfident.
  context:
    - write_report
    - verify_claims

edit_report:
  description: "Produce a corrected final report."
  agent: editor
  expected_output: >
    The report given from the write_report task, but corrected for mistakes.
  context:
    - write_report
    - verify_claims
    - skeptic_review
